default: &default
  adapter: sqlite3
  encoding: unicode
  pool: 5
  username: sqlite3

development:
  <<: *default
  database: db/rangoli_dev.sqlite3

test:
  <<: *default
  database: db/rangoli_test.sqlite3

production:
  <<: *default
  database: db/rangoli_prod.sqlite3
